version: "3.8"

services:
  api:
    build:
      context: ./code
      dockerfile: api.Dockerfile
    ports:
      - 127.0.0.1:8000:80
    volumes:
      - ./code:/code
      - ./uploaded_images:/uploaded_images
      - ./generated_images:/static
    depends_on:
      - mongo
      - worker1
      - worker2
      - worker3
      - worker4

  worker1:
    build:
      context: ./code
      dockerfile: worker1.Dockerfile
    volumes:
      - ./code:/code
      - ./uploaded_images:/uploaded_images
      - ./generated_images:/generated_images
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      HUGGING_FACE_HUB_TOKEN: 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
    depends_on:
      - redis1
      - mongo
    ipc: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  redis1:
    image: redis:7-alpine

  worker2:
    build:
      context: ./code
      dockerfile: worker2.Dockerfile
    volumes:
      - ./code:/code
      - ./uploaded_images:/uploaded_images
      - ./generated_images:/generated_images
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      HUGGING_FACE_HUB_TOKEN: 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
    depends_on:
      - redis2
      - mongo
    ipc: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  redis2:
    image: redis:7-alpine

  worker3:
    build:
      context: ./code
      dockerfile: worker3.Dockerfile
    volumes:
      - ./code:/code
      - ./uploaded_images:/uploaded_images
      - ./generated_images:/generated_images
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      HUGGING_FACE_HUB_TOKEN: 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
    depends_on:
      - redis3
      - mongo
    ipc: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  redis3:
    image: redis:7-alpine

  worker4:
    build:
      context: ./code
      dockerfile: worker4.Dockerfile
    volumes:
      - ./code:/code
      - ./uploaded_images:/uploaded_images
      - ./generated_images:/generated_images
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      HUGGING_FACE_HUB_TOKEN: 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
    depends_on:
      - redis4
      - mongo
    ipc: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  redis4:
    image: redis:7-alpine

  mongo:
    image: mongo
    restart: always
    # ports:
    #   - 127.0.0.1:27017:27017
    volumes:
      - ./db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
